package com.fc.map.model;

import java.io.Serializable;
import java.util.Date;

public class Map implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map.x
     *
     * @mbg.generated
     */
    private String x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map.y
     *
     * @mbg.generated
     */
    private String y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map.xy
     *
     * @mbg.generated
     */
    private String xy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map.provision
     *
     * @mbg.generated
     */
    private String provision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map.index
     *
     * @mbg.generated
     */
    private Integer index;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map.program
     *
     * @mbg.generated
     */
    private String program;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_map.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_map
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map.id
     *
     * @return the value of t_map.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map.id
     *
     * @param id the value for t_map.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map.x
     *
     * @return the value of t_map.x
     *
     * @mbg.generated
     */
    public String getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map.x
     *
     * @param x the value for t_map.x
     *
     * @mbg.generated
     */
    public void setX(String x) {
        this.x = x == null ? null : x.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map.y
     *
     * @return the value of t_map.y
     *
     * @mbg.generated
     */
    public String getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map.y
     *
     * @param y the value for t_map.y
     *
     * @mbg.generated
     */
    public void setY(String y) {
        this.y = y == null ? null : y.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map.xy
     *
     * @return the value of t_map.xy
     *
     * @mbg.generated
     */
    public String getXy() {
        return xy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map.xy
     *
     * @param xy the value for t_map.xy
     *
     * @mbg.generated
     */
    public void setXy(String xy) {
        this.xy = xy == null ? null : xy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map.name
     *
     * @return the value of t_map.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map.name
     *
     * @param name the value for t_map.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map.address
     *
     * @return the value of t_map.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map.address
     *
     * @param address the value for t_map.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map.provision
     *
     * @return the value of t_map.provision
     *
     * @mbg.generated
     */
    public String getProvision() {
        return provision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map.provision
     *
     * @param provision the value for t_map.provision
     *
     * @mbg.generated
     */
    public void setProvision(String provision) {
        this.provision = provision == null ? null : provision.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map.index
     *
     * @return the value of t_map.index
     *
     * @mbg.generated
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map.index
     *
     * @param index the value for t_map.index
     *
     * @mbg.generated
     */
    public void setIndex(Integer index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map.program
     *
     * @return the value of t_map.program
     *
     * @mbg.generated
     */
    public String getProgram() {
        return program;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map.program
     *
     * @param program the value for t_map.program
     *
     * @mbg.generated
     */
    public void setProgram(String program) {
        this.program = program == null ? null : program.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_map.date
     *
     * @return the value of t_map.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_map.date
     *
     * @param date the value for t_map.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}